version: '3'


services:
  builder:
    build:
      context: ../
      dockerfile: ./docker/builder/Dockerfile
    volumes:
      - mnt:/mnt
  webserver:
    build:
      context: ../
      dockerfile: ./docker/webserver/Dockerfile
    volumes:
      - mnt:/mnt
    ports:
      - "8087:8080"
volumes:
  mnt: {}
